<?php


namespace App\Data\DataTransferObjects;


class TreeMapChartData extends GoogleChartData
{
    protected string $id;
    protected ?string $parentId;
    protected int $size;
    protected ?int $color = null;

    protected array $labels = [
        'id'=>'종목',
        'parentId'=>'업종/테마',
        'size'=>'시가총액',
        'color'=>'상승/하락'
    ];

    /**
     * @return string
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * @param string $id
     * @return TreeMapChartData
     */
    public function setId(string $id): TreeMapChartData
    {
        $this->id = $id;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getParentId(): ?string
    {
        return $this->parentId;
    }

    /**
     * @param string|null $parentId
     * @return TreeMapChartData
     */
    public function setParentId(?string $parentId): TreeMapChartData
    {
        $this->parentId = $parentId;
        return $this;
    }

    /**
     * @return int
     */
    public function getSize(): int
    {
        return $this->size;
    }

    /**
     * @param int $size
     * @return TreeMapChartData
     */
    public function setSize(int $size): TreeMapChartData
    {
        $this->size = $size;
        return $this;
    }

    /**
     * @return int|null
     */
    public function getColor(): ?int
    {
        return $this->color;
    }

    /**
     * @param int|null $color
     * @return TreeMapChartData
     */
    public function setColor(?int $color): TreeMapChartData
    {
        $this->color = $color;
        return $this;
    }

    /**
     * @return array|string[]
     */
    public function getLabels(): array
    {
        return $this->labels;
    }

    /**
     * @param array|string[] $labels
     * @return TreeMapChartData
     */
    public function setLabels(array $labels): TreeMapChartData
    {
        $this->labels = $labels;
        return $this;
    }

    public function toArray(bool $allowNull = true): ?array
    {
        return parent::toArray($allowNull); // TODO: Change the autogenerated stub
    }
}
